### ISSUE TITLE
Exposure Logging switched off, impossible to keep switched on

### ISSUE THREAD

**Issue by RAWes** [covid-be-app/cwa-app-ios#211]
I installed the beta app on my iPhone on 21/9, and it worked for two days. On the evening of 23/9, I noticed that Exposure logging had stopped and the last update was from 17:05. I used the button Activate Exposure Logging to go to the Logging view and I moved the Exposure Logging slider to the right to switch it on, and the slider turned green, as expected. However, after using the Back button to go to the main view, Exposure logging was still on 'stopped'. I tried this several times and the result is always the same, it is impossible to switch on Exposure Logging and keep it on. If I move the slider to on and then switch to another application (without using the Back button), the slider is back to off when I come back to the app. If I switch off the phone's screen while still in the Logging view (or let it switch off by itself automatically), the slider is back to off when I open the phone again. So without Exposure Logging, I no longer have a functioning app at the moment.

- iOS Version:  13.7
- Device: iPhone SE

And then this: do we beta testers really have to go through github to report bugs? The only contact address I found in the app (coronalert@sciensano.be) gave me a standard reply, saying that the development of the app is a responsibility of the regions, in other words: don't come to us. A beta version that is largely distributed (10,000 users) should have an accessible place where bug reports can be filed, github will be a big hurdle for many of the beta testers.

**Comment by ir-fuel** [comment]
Beta testers should not go through Github to report bugs. Bugs and remarks for the beta build should be reported through Testflight, for iOS.

Can you please contact me on joris@devside.com so we can look into this issue together?

Thanks

**Comment by ir-fuel** [comment]
It seems the problem disappeared by itself.
