### ISSUE TITLE
iOS Widgets with stats/exposure

### ISSUE THREAD

**Issue by flying-sausages** [covid-be-app/cwa-app-ios#233]
## Avoid duplicates

* [x] This issue has not already been raised before

## Current Implementation
N/A

## Suggested Enhancement
Add iOS 14 widgets that user can add to the Home Screen. This could contain the daily stats (Belgium and or World), the current stats or the current exposure level of the user.

## Expected Benefits
1. There are no apps on the market which have Coronavirus stats as widgets. This would be the first one as far as I know.
2. Widgets are something people obviously want, one of the widget creation apps is currently n3 on the Belgian App Store. This would increase the promotional side of the app.
3. The widgets themselves would be informative.

**Comment by ir-fuel** [comment]
Thanks for the suggestion. 
For privacy reasons we will never show exposure risk status or test results on the Home Screen. The user will only be able to see those inside the app. If something important happens (e.g. a high risk detection) a notification will appear on the phone but without any details. This is for privacy reasons.

The Coronavirus stats is indeed a possibility. I will pass this suggestion to business

**Comment by flying-sausages** [comment]
Hey, thanks for the reply. I looked at "upstream" and found this Issue together with actual implementation commits, might be a nice reference for later.

https://github.com/corona-warn-app/cwa-wishlist/issues/26

Could you please develop on why the exposure risk would be information that should not show on the home screen for privacy reasons? I'm working with the assumption that if a bank can show me a widget with my balance, I should be able to see the information which you can see in the mockups in the issue linked above. Exposure risk isn't identifiable information, and the data itself is not protected inside of the app by any passcode or biometric mechanism either. i.e. if someone has access to a user's homescreen, nothing prevents them form launching the app and viewing this information anyway.

In the case of actual test results, you're absolutley right and I agree with you there. After all, it's also not something that's likely to change very often or something you might need to remind yourself with... When you get the results you're definitely going to remember what they were ha.

**Comment by ir-fuel** [comment]
Indeed, you are right about the Home Screen widget. What I stated was about when the widget was on the lock screen (like weather, and battery status). In that case the same security restrictions apply. If you can access the Home Screen you can access the app.

As you can see from the upstream issue, it's not a straightforward task to do this (we need to open a connection between the widget and the database in the Coronalert app).

**Comment by ir-fuel** [comment]
This has been moved to the internal issue tracker for discussion with business
