### ISSUE TITLE
Weird English string while test results not available

### ISSUE THREAD

**Issue by flying-sausages** [covid-be-app/cwa-app-ios#241]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronalert.be)
* [x] Bug is not already reported in another issue

## Describe the bug
The "Result not" is probably a string wrapping and cutting off.
![image](https://user-images.githubusercontent.com/23618693/95110250-064cdf00-073e-11eb-9b58-7e92208328b3.jpeg)
## Expected behaviour

A coherent phrase in place of "Result Not"

## Steps to reproduce the issue

1. Open app
2. Click the "Add test" (Cannot recall what the option to insert data was called in English)
3. See screen above

## Technical details

- iOS Version: 14.0.1
- Device: iPhone 11

## Possible Fix

Change language string to something short and concise? Maybe "Not available"? Maybe increase the size on the text element to allow for more space?

**Comment by ir-fuel** [comment]
Thanks for reporting.

This has been fixed already in the latest version of the code and will be solved in the next release.

![IMG_1039](https://user-images.githubusercontent.com/1573715/95117235-89733280-0748-11eb-85f0-e4789c1d7980.PNG)
