### ISSUE TITLE
IOS 14.2 beta

### ISSUE THREAD

**Issue by Neled77** [covid-be-app/cwa-app-ios#254]
IOS version off app gives some errors in IOS 14.2 beta.

Error 11: Something went wrong. Your level of risk cannot best  determinated.

-> Already removed the app
-> restarted the phone

Best regards

Alex

**Comment by ir-fuel** [comment]
Hello

Unfortunately we can't help you with problems related to beta versions of iOS.

Thanks for your understanding.

**Comment by Neled77** [comment]
Just wanted to let you know as 14.2 might be the next release.

Regards

Alex

**Comment by ir-fuel** [comment]
And that's appreciated :) 

It's just that from the text itself we can't derive if you are actually expecting help from us in solving the issue in order to have a working version on your device. But you can be assured it will be looked into.

**Comment by Neled77** [comment]
True, sorry, I’m not expecting a fix on beta versions 😊.
Just wanted to give you the feedback.
Good luck and thanks for the app!!
Regards

Alex
