### ISSUE TITLE
Logging error ios 14.2

### ISSUE THREAD

**Issue by MrHR** [covid-be-app/cwa-app-ios#274]
## Describe the bug

Elke keer ik de app open krijg ik de boodschap: “An error occured during exposure logging: EN code 2” 
![0270EC1F-9DDE-4090-96C0-505ECAFD14B2](https://user-images.githubusercontent.com/5786082/96708879-26b1a600-139a-11eb-9514-f53ada613bed.png)

nu ook gevolgd door

![A353919A-BB94-4C74-94E1-3EF140EF291E](https://user-images.githubusercontent.com/5786082/96708895-2dd8b400-139a-11eb-8fda-dff728f6ab35.png)

Dit is al een aantal dagen zo. Ik heb geen idee hoe deze bug te reproduceren en heb de app nog niet geherinstalleerd omdat ik mijn vorige logs niet kwijt wil.

Ik zit op de ios 14.2 beta op een iphone 7

**Comment by ir-fuel** [comment]
Dubbel van

https://github.com/covid-be-app/cwa-app-ios/issues/263
