### ISSUE TITLE
Exposure logging always shows active 13/14 days even while active 14+ days

### ISSUE THREAD

**Issue by jpweytjens** [covid-be-app/cwa-app-ios#286]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronalert.be)

* [x] Bug is not already reported in another issue

## Describe the bug

I have installed the Coronalert app and enabled logging on 29/09/2020. The last few days I noticed the app always mentions `Exposure logging was active for 13 of the past 14 days`, despite being active for more than 14 days. See the screenshot attached below.

## Expected behaviour

I expect the app to say exposure logging was active for 14 out of 14 days.

## Steps to reproduce the issue

1. Install app and enable exposure logging
2. Wait 14 days with bluetooth enabled
3. Open Coronalert app
4. See message shown below ![screenshot](https://user-images.githubusercontent.com/34494702/97457841-6b10e900-193a-11eb-8fe0-b1618a53e879.PNG)

-->

## Technical details

- iOS Version: iOS 14 and iOS 14.1 (since 20/10/20)
- Device: iPhone XR

## Additional context

I check the application regularly, but not daily. Hence I do not know for certain if the app showed 14/14 days at some point or not. I have updated iOS from version 14 to 14.1 and I have installed all the updates to the Coronalert app. Beyond this, I have not changed anything to the app or the phone. Bluetooth is always enabled except for brief < 2 minutes intervals from time to time to disconnect other devices.

**Comment by jpweytjens** [comment]
After multiple days of 13/14, the app now mentions exposure logging was permanently active. I have no idea what changed in these last few days. 

![image](https://user-images.githubusercontent.com/34494702/97688755-e2f62500-1a9a-11eb-9bdd-1f06b56912f2.png)

**Comment by ir-fuel** [comment]
Hello

Can you check in:

Settings/ Exposure Notifications / Exposure Logging Status / Exposure Checks

and see if there are any days missing in that list?

**Comment by ir-fuel** [comment]
Settings -> iPhone Settings app

**Comment by jpweytjens** [comment]
Yes, the 20th of October is missing even though I used my phone that day.

![Exposure checks](https://user-images.githubusercontent.com/34494702/97784916-369f6600-1ba2-11eb-997f-4bf946293c8c.png)
![Screen Time 20th of October](https://user-images.githubusercontent.com/34494702/97784917-399a5680-1ba2-11eb-80be-3c62382ca607.jpeg)
