### ISSUE TITLE
Are failed dummy requests reliably retransmitted?

### ISSUE THREAD

**Issue by gunesacar** [covid-be-app/cwa-app-ios#360]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronalert.be)
* [x] Question has not already been asked in another issue

## Your Question

* Source File: https://github.com/covid-be-app/cwa-app-ios/blob/master/src/xcode/ENA/BE/FakeRequests/BEFakeRequestsExecutor.swift
* Line(s): -
* Question: Hello!

I'm helping Prof. Bart Preneel to calculate the active number of Coronalert users.

The method I'm looking into is similar to [the Swiss method](https://www.experimental.bfs.admin.ch/expstat/en/home/innovative-methods/swisscovid-app-monitoring.assetdetail.13667538.html), which is based on the number of daily dummy requests received on the backend.

I am wondering if the following statement mentioned in [the Swiss document](https://www.experimental.bfs.admin.ch/bfsstatic/dam/assets/13667538/master) is also valid for the Coronalert iOS app:
> It should be noted that if the device is not active or is not connected to the internet, the dummy request is transmitted later on.

That is, does the Coronalert iOS app resend dummy requests that are failed due to connectivity (or other) issues? I'm particularly interested in cases where the phone remains disconnected for long hours  -- e.g. when the phone is in airplane mode through the night.

Thank you so much!
PS: Here's the same question on [the Coronalert Android app](https://github.com/covid-be-app/cwa-app-android/issues/132)

**Comment by ir-fuel** [comment]
They are not cached or counted, no. It's executed when iOS decides to wake the app up to do the background checks. If the phone is off for a long time nothing will happen, and when it's powered on later it will continue like before, there is no "catching up" going on, ever.

**Comment by gunesacar** [comment]
Thank you.
